# Travis CI integration for p4c using Docker.

services:
  - docker

env:
  - CTEST_PARALLEL_LEVEL=4

install:
  - docker build -t p4c --build-arg IMAGE_TYPE=test .

script:
  - docker run -w /p4c/build -e CTEST_PARALLEL_LEVEL p4c ctest --output-on-failure --schedule-random
